version: "3"

services:
  db:
    image: mysql:5.7.16
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD: pass1234
      - MYSQL_DATABASE: icts_test
      - MYSQL_USER: root
    ports:
      - "3308:3306"
